version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Begining Maven build
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
      
artifacts:
  files:
    - target/*.jar
    - target/surefire-reports/**
    - target/failsafe-reports/**
  discard-paths: no