version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      
artifacts:
  files:
    - target/dependency/**
    - target/*.jar
    - target/surefire-reports/**
    - target/failsafe-reports/**
  discard-paths: no